/*
 * Time_Interleaver_h.h
 *
 *  Created on: 30 May 2017
 *      Author: JULIAN MORTIMER
 */

#ifndef TIME_INTERLEAVER_H_H_
#define TIME_INTERLEAVER_H_H_

//#define TIME_INTERLEAVER_BUF_SIZE  ( 32768 )
//#define TIME_INTERLEAVER_N_SLAVE_REGS ( 16 )
//
//#define TIME_INTERLEAVER_BASE_ADDR           ( 0x00000000 )
//
//#define TIME_INTERLEAVER_CTRL_REG            ( 0 )
//#define TIME_INTERLEAVER_N_DATA_WORDS_RX_REG ( 1 )
//#define TIME_INTERLEAVER_N_DATA_WORDS_TX_REG ( 2 )
//#define TIME_INTERLEAVER_RX_START_ADDR_REG   ( 3 )
//#define TIME_INTERLEAVER_TX_START_ADDR_REG   ( 4 )
//#define TIME_INTERLEAVER_AD_RD_WR_ADDR_REG   ( 5 )
//#define TIME_INTERLEAVER_AD_WR_DATA_REG      ( 6 )
//
//#define TIME_INTERLEAVER_STATUS_REG          ( 8 )
//#define TIME_INTERLEAVER_AD_INTLVR_RD_REG    ( 9 )
//#define TIME_INTERLEAVER_AD_TX_BUF_RD_REG    ( 10 )
//
//#define TIME_INTERLEAVER_SOFT_RESET          ( 0x00000001 )
//#define TIME_INTERLEAVER_INT_ACK             ( 0x00000002 )
//#define TIME_INTERLEAVER_START               ( 0x00000004 )
//#define TIME_INTERLEAVER_ENTER_ADMIN         ( 0x00000008 )
//#define TIME_INTERLEAVER_EXIT_ADMIN          ( 0x00000010 )
//#define TIME_INTERLEAVER_AD_WR_INTLVR        ( 0x00000020 )
//#define TIME_INTERLEAVER_AD_WR_RX_BUF        ( 0x00000040 )
//#define TIME_INTERLEAVER_AD_RD_INTLVR        ( 0x00000080 )
//#define TIME_INTERLEAVER_AD_RD_TX_BUF        ( 0x00000100 )
//#define TIME_INTERLEAVER_AD_RD_INTLVR_ACK    ( 0x00000200 )
//#define TIME_INTERLEAVER_AD_RD_TX_BUF_ACK    ( 0x00000400 )
//
//
//#define TIME_INTERLEAVER_PS_RESET            ( 0x00000001 )
//#define TIME_INTERLEAVER_IRQ                 ( 0x00000002 )
//#define TIME_INTERLEAVER_RX_FRAME_DONE       ( 0x00000004 )
//#define TIME_INTERLEAVER_TX_FRAME_DONE       ( 0x00000008 )
//#define TIME_INTERLEAVER_AD_INTLVR_RD_RDY    ( 0x00000010 )
//#define TIME_INTERLEAVER_AD_TX_BUF_RD_RDY    ( 0x00000020 )


#endif /* TIME_INTERLEAVER_H_ */
