
 PARAMETER VERSION = 2.2.0


BEGIN OS
 PARAMETER OS_NAME = standalone
 PARAMETER OS_VER = 5.3
 PARAMETER PROC_INSTANCE = ps7_cortexa9_0
 PARAMETER stdin = ps7_uart_1
 PARAMETER stdout = ps7_uart_1
END


BEGIN PROCESSOR
 PARAMETER DRIVER_NAME = cpu_cortexa9
 PARAMETER DRIVER_VER = 2.1
 PARAMETER HW_INSTANCE = ps7_cortexa9_0
END


BEGIN DRIVER
 PARAMETER DRIVER_NAME = GM_Simple_Timer
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = GM_Simple_Timer_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = AXI4_Stream_Data_Sink
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = NSD_ABS_DATA_SINK_0_DATA_SINK
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = AXI4_Stream_Data_Sink
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = NSD_ABS_DATA_SINK_1_DATA_SINK
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = AXI4_Stream_Data_Sink
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = NSD_ABS_DATA_SINK_2_DATA_SINK
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = AXI4_Stream_Data_Sink
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = NSD_BCAST_DATA_SINK_0_DATA_SINK
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = AXI4_Stream_Data_Sink
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = NSD_BCAST_DATA_SINK_1_DATA_SINK
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = AXI4_Stream_Data_Sink
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = NSD_BCAST_DATA_SINK_2_DATA_SINK
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = AXI4_Stream_Data_Sink
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = NSD_CORDIC_DATA_SINK_AXI4_Stream_Data_Sink_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = AXI4_Stream_Data_Sink
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = NSD_DTA_DATA_SINK_RX_RAW_DATA_SINK
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = AXI4_Stream_Data_Sink
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = NSD_FFT_DATA_SINK_AXI4_Stream_Data_Sink_1
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = AXI4_Stream_Data_Sink
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = NSD_PRS_DATA_SINK_RX_RAW_DATA_SINK
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = FFT_Controller
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = NULL_SYMBOL_DET_NSD_MOVING_MAG_SQUARED_FFT_Controller_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = NULL_SYMBOL_DETECTOR
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = NULL_SYMBOL_DET_NULL_SYMBOL_DETECTOR_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = Freq_Ctr
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = RF_CHANNEL_EMULATOR_Emul_Clk_Freq_Ctr
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 2.0
 PARAMETER HW_INSTANCE = RF_CHANNEL_EMULATOR_Emul_Clk_Gen
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = DEMODULATOR
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = RF_CHANNEL_EMULATOR_RF_CHAN_EMULATOR
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = AXI4_Stream_Device_Bypass
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = RF_CHANNEL_EMULATOR_Tx_Rx_Emulator_Switch
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = Freq_Ctr
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = RF_INTERFACE_ad9364_adc_frq_ctr
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = Freq_Ctr
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = RF_INTERFACE_ad9364_clk_frq_ctr
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = Freq_Ctr
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = RF_INTERFACE_ad9364_dac_frq_ctr
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 2.0
 PARAMETER HW_INSTANCE = RF_INTERFACE_axi_ad9361_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = AXI4_Stream_Data_Sink
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = TIME_DOMAIN_DATA_SINK_RX_RAW_DATA_SINK
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = Training_Symbol_Injector
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = TRAINING_SYMB_INJECTOR_Training_Symbol_Injector_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = FFT_Controller
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = TX_DATA_FFT_FFT_Controller_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = AXI4_Stream_Data_Source
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = TX_DATA_SOURCE_AXI4_Stream_Data_Source
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = GM_AXI_BRAM_Controller
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = TX_DATA_SOURCE_GM_AXI_BRAM_Controller_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = bram
 PARAMETER DRIVER_VER = 4.0
 PARAMETER HW_INSTANCE = axi_bram_ctrl_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 2.0
 PARAMETER HW_INSTANCE = ps7_afi_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 2.0
 PARAMETER HW_INSTANCE = ps7_afi_1
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 2.0
 PARAMETER HW_INSTANCE = ps7_afi_2
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 2.0
 PARAMETER HW_INSTANCE = ps7_afi_3
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = coresightps_dcc
 PARAMETER DRIVER_VER = 1.2
 PARAMETER HW_INSTANCE = ps7_coresight_comp_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = ddrps
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = ps7_ddr_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 2.0
 PARAMETER HW_INSTANCE = ps7_ddrc_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = devcfg
 PARAMETER DRIVER_VER = 3.3
 PARAMETER HW_INSTANCE = ps7_dev_cfg_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = dmaps
 PARAMETER DRIVER_VER = 2.1
 PARAMETER HW_INSTANCE = ps7_dma_ns
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = dmaps
 PARAMETER DRIVER_VER = 2.1
 PARAMETER HW_INSTANCE = ps7_dma_s
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = emacps
 PARAMETER DRIVER_VER = 3.1
 PARAMETER HW_INSTANCE = ps7_ethernet_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 2.0
 PARAMETER HW_INSTANCE = ps7_globaltimer_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = gpiops
 PARAMETER DRIVER_VER = 3.1
 PARAMETER HW_INSTANCE = ps7_gpio_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 2.0
 PARAMETER HW_INSTANCE = ps7_gpv_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = iicps
 PARAMETER DRIVER_VER = 3.0
 PARAMETER HW_INSTANCE = ps7_i2c_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 2.0
 PARAMETER HW_INSTANCE = ps7_intc_dist_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 2.0
 PARAMETER HW_INSTANCE = ps7_iop_bus_config_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 2.0
 PARAMETER HW_INSTANCE = ps7_l2cachec_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 2.0
 PARAMETER HW_INSTANCE = ps7_ocmc_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 2.0
 PARAMETER HW_INSTANCE = ps7_pl310_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 2.0
 PARAMETER HW_INSTANCE = ps7_pmu_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = qspips
 PARAMETER DRIVER_VER = 3.2
 PARAMETER HW_INSTANCE = ps7_qspi_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 2.0
 PARAMETER HW_INSTANCE = ps7_qspi_linear_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 2.0
 PARAMETER HW_INSTANCE = ps7_ram_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 2.0
 PARAMETER HW_INSTANCE = ps7_ram_1
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 2.0
 PARAMETER HW_INSTANCE = ps7_scuc_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = scugic
 PARAMETER DRIVER_VER = 3.1
 PARAMETER HW_INSTANCE = ps7_scugic_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = scutimer
 PARAMETER DRIVER_VER = 2.1
 PARAMETER HW_INSTANCE = ps7_scutimer_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = scuwdt
 PARAMETER DRIVER_VER = 2.1
 PARAMETER HW_INSTANCE = ps7_scuwdt_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = sdps
 PARAMETER DRIVER_VER = 2.6
 PARAMETER HW_INSTANCE = ps7_sd_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 2.0
 PARAMETER HW_INSTANCE = ps7_slcr_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = spips
 PARAMETER DRIVER_VER = 3.0
 PARAMETER HW_INSTANCE = ps7_spi_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = uartps
 PARAMETER DRIVER_VER = 3.1
 PARAMETER HW_INSTANCE = ps7_uart_1
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = usbps
 PARAMETER DRIVER_VER = 2.2
 PARAMETER HW_INSTANCE = ps7_usb_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = xadcps
 PARAMETER DRIVER_VER = 2.2
 PARAMETER HW_INSTANCE = ps7_xadc_0
END


